name: continuous-integration
on:
  push:
    branches:
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

  codecov:
    needs: [checkout, docker]
    runs-on: ubuntu-latest
    steps:     
      - name: Build Tests 
        run: docker build -t tests --target test
      - name: Run Tests 
        run: docker run -v "${PWD}/:/tests/" tests
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  docker:
    uses: BooAIPublic/github-workflows/.github/workflows/build-and-push.yml@master
    with:
      image: "smixers/fomodog"
      dockerfile: ./Dockerfile
      context: .
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          